http:
  routers:
    api:
      rule: "PathPrefix(`/api`)"
      entryPoints: [web]
      service: api
      priority: 10
    web:
      rule: "PathPrefix(`/`)"
      entryPoints: [web]
      service: web
      priority: 1
  services:
    api:
      loadBalancer:
        servers:
          - url: "http://api:3000"
    web:
      loadBalancer:
        servers:
          - url: "http://web:4321"
