import { Hono } from "hono";
import templates from "../data/marketplace-templates.json";
import { requireAuth } from "../lib/auth-middleware";

export const marketplace = new Hono();

marketplace.use("*", requireAuth);

// Static catalog, regenerated by `bun run scripts/fetch-marketplace-templates.ts` (see private/PLAN.md,
// "Fase 3 / Marketplace") — no network calls at request time.
marketplace.get("/", (c) => c.json(templates));
